// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhoneBook.proto

package be.cloud;

public interface PhoneNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.PhoneNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <pre>
   *PhoneType type = 4 [default = MOBILE];
   * </pre>
   *
   * <code>.be.cloud.PhoneType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   *PhoneType type = 4 [default = MOBILE];
   * </pre>
   *
   * <code>.be.cloud.PhoneType type = 2;</code>
   */
  be.cloud.PhoneType getType();
}
