// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhoneBook.proto

package be.cloud;

public final class PhoneBookOuterClass {
  private PhoneBookOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_Success_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_Success_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PhoneBook.proto\022\010be.cloud\"X\n\006Person\022\014\n" +
      "\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022%" +
      "\n\006number\030\004 \001(\0132\025.be.cloud.PhoneNumber\"@\n" +
      "\013PhoneNumber\022\016\n\006number\030\001 \001(\t\022!\n\004type\030\002 \001" +
      "(\0162\023.be.cloud.PhoneType\"\032\n\007Success\022\017\n\007su" +
      "ccess\030\001 \001(\010*+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004" +
      "HOME\020\001\022\010\n\004WORK\020\0022\277\001\n\tPhoneBook\0220\n\taddPer" +
      "son\022\020.be.cloud.Person\032\021.be.cloud.Success" +
      "\022?\n\024getPhoneNumberByName\022\020.be.cloud.Pers" +
      "on\032\025.be.cloud.PhoneNumber\022?\n\024getNameByPh" +
      "oneNumber\022\025.be.cloud.PhoneNumber\032\020.be.cl" +
      "oud.PersonB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_be_cloud_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_be_cloud_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Number", });
    internal_static_be_cloud_PhoneNumber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_be_cloud_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_be_cloud_Success_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_be_cloud_Success_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_Success_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
